#!/bin/bash
logFile=${2}

source $(dirname $(readlink -m $0))/task_source

[[ $# -lt 1 ]] && {
cat << EOF
task - Run command(s) with output to
       file/stream with progress indicator

Usage: task <commands string> [log file]
    log file will default to /dev/null.
EOF
exit 1
}

commands=$1

# chops command preview to 25 chars
function message()
{
    local s=${commands:0:25}
    if (( ${#commands} >= 25 )); then
        s="$s..."
    fi
    printf "%s" "$s"
}

# If the command contains sudo, authorize first
if [[ "$commands" =~ "sudo" ]];
then
    sudo -v || exit 1
fi

eval "$commands" &>> $logFile & waitProgress "$(message) > $logFile" || echo "Command failed"
