#!/bin/bash
# Host repo to web
[ "$1" == "help" -o "$1" == ".." -o "$1" == "." ] && {
    echo "Usage: $(basename $0) <action>"
    echo "actions: 'help', 'stop', 'start' (default)"
    exit 1
}

ACTION=$1
HTTPD=
PS3="Select repo: "
REPO=

which apache2 &>/dev/null
if [ $? -eq 0 ] ; then
    HTTPD=apache2
else
    which lighttpd &>/dev/null
    [ $? -eq 0 ] && HTTPD=lighttpd
fi

[ -z $HTTPD ] && {
    echo "Error, apache2 or lighttpd not found"
    exit 1
}

select dir in $(ls -t | grep -v -E '(git-shell|backups)'); do
    if [ -n "$dir" ] ; then 
        cd "$dir"
        break
    fi
done

case "$ACTION" in 
    STOP|Stop|stop)
        git instaweb --stop
        ;;
    *)
        git instaweb --httpd $HTTPD -b null 2>/dev/null
        ;;
esac
