#!/bin/sh
# Add pub key
read key
keyfile=$(mktemp)
echo "$key" > $keyfile

# Generate a fingerprint
ssh-keygen -lf $keyfile || {
    echo "Error: Not a Keyfile"
    rm $keyfile
    exit 1
}

cat "$keyfile" >> "$HOME"/.ssh/authorized_keys
rm $keyfile

echo "Success! Added a key with the following fingerprint:"
echo $fingerprint
