#!/bin/bash
# Lists pub keys
echo "AUTHORIZED KEYS"
echo "---------------"
tmp=$(mktemp)
cat "$HOME"/.ssh/authorized_keys | while read key; do
  echo "$key" > "$tmp"
  ssh-keygen -lf "$tmp"
done
rm "$tmp"
