#!/bin/bash
# Print Repo Log
[ -z "$1" -o "$1" == ".." -o "$1" == "." ] && {
    echo "Usage: $(basename $0) <repo> <branch>"
    exit 1
}

cd "$1"
branch="$2"

[[ -z $branch ]] && branch='master'

! git branch | grep "$branch\$" &>/dev/null && {
    echo "Branch '$branch' not found"
    exit 1
}

git log "$branch" --pretty=format:'%Cgreen%h | %Cblue%an | %Cred%ad | %Creset- %s' -30 | column -t -s '|' 2>/dev/null
exit 0
