#!/bin/bash
# Mirrors Repo
[ -z "$1" -o "$1" == ".." -o "$1" == "." ] && {
    echo "Usage: $(basename $0) <repo>"
    exit 1
}

[[ -d "$1" ]] && {
    echo "Repo '$1' already exists."
    exit 1
}

echo -ne "Remote: "
read remote

echo -ne "Description: "
read desc

echo -ne "Owner: "
read owner

git clone --mirror $remote "$1" || exit 1
cd "$1"

echo -ne "\n[gitweb]\nowner = ${owner}\n" >> config
echo "$desc" > description
touch _mirror

cd ..
bash git-shell-commands/update "$1"

exit 0
