#!/bin/bash
# Removes Repo
[ -z "$1" -o "$1" == ".." -o "$1" == "." ] && {
    echo "Usage: $(basename $0) <repo>"
    exit 1
}

[[ ! -d $1 ]] && {
    echo "Repo '$1' does not exist."
    exit 1
}

echo -ne "Delete '$1' [y/n]?: "
read ans

# Attempts to prevent going outside pwd
case "$ans" in
    Yes|yes|y)
        "$HOME"/git-shell-commands/tar "$1" || {
            echo "Backup error."
            exit 1
        }

        rm -rf "$1" || error "Remove error."
        echo "Remove succeeded."
        ;;
    *)
        echo "Remove aborted."
        ;;
esac
exit 0
