#!/bin/bash
# Removes Repo

error(){
    echo "$1"
    exit 1
}

[ -z "$1" -o "$1" == ".." -o "$1" == "." ] && {
    echo "Usage: $(basename $0) <dir name>"
    exit 1
}

echo -ne "Delete '"$1"' [y/n]?: "
read ans

# Attempts to prevent going outside pwd
case "$ans" in
    Yes|yes|y)
        ls -A | grep "$1" > /dev/null
        [ "$?" != "0" ] && error "Dir '$1' does not exist."
        [ ! -d "$1" ] && error "'$1' is not a directory"

        $HOME/git-shell-commands/tar "$1" || {
            error "Backup error."
            exit 1
        }

        rm -rf "$1" || error "Remove error."
        echo "Remove succeeded."
        ;;
    *)
        echo "Remove aborted."
        ;;
esac
exit 0
