#!/bin/bash
# Creates Repo
[ -z "$1" -o "$1" == ".." -o "$1" == "." ] && {
    echo "Usage: $(basename $0) <repo>"
    exit 1
}

[[ -d "$1" ]] && {
    echo "Repo '$1' already exists."
    exit 1
}


echo -ne "Description: "
read desc

echo -ne "Owner: "
read owner

mkdir "$1" ; cd "$1"
git init --bare || exit 1

echo -ne "\n[gitweb]\nowner = ${owner}\n" >> config
echo "$desc" > description

exit 0
