#!/bin/bash
# Updates mirror
[ -z "$1" -o "$1" == ".." -o "$1" == "." ] && {
    echo "Usage: $(basename $0) <repo>"
    exit 1
}

[[ ! -d "$1" ]] && {
    echo "Repo '$1' doesnt exists."
    exit 1
}

cd "$1"
git remote update --prune || exit 1

exit 0
